name: PdxTrackRouter
main: com.gmail.emertens.pdxtrackrouter.PdxTrackRouter
version: 0.6
description: Automatically route minecarts down tracks. 
author: glguy
load: POSTWORLD
website: http://dev.bukkit.org/server-mods/pdxtrackrouter/

commands:
  destination:
    description: Set destination to take at junctions
    usage: /<command> [DIRECTION]
  changesign:
    description: Set a line on a sign
    usage: /<command> [1-4] TEXT
    permission: trackrouter.changesign
  junctions:
    description: Compute the junctions visible along the track
    permission: trackrouter.junctions
    usage: /<command>

permissions:
  trackrouter.changesign:
    description: Change lines on signs in-place
    default: op
  trackrouter.junctions:
    description: Execute the junctions command
    default: op
