name: PdxTrackRouter
main: com.gmail.emertens.pdxtrackrouter.PdxTrackRouter
version: 0.8
description: Automatically route minecarts down tracks. 
author: glguy
load: POSTWORLD
website: http://dev.bukkit.org/server-mods/pdxtrackrouter/

commands:
  destination:
    description: Set destination to take at junctions
    usage: /<command> [DIRECTION]
    permission: trackrouter.destination
  changesign:
    description: Set a line on a sign
    usage: /<command> [1-4] TEXT
    permission: trackrouter.changesign
  junctions:
    description: Compute the junctions visible along the track
    permission: trackrouter.junctions
    usage: /<command>
  junction:
    description: Edit junction signs in place
    permission: trackrouter.sign.junction.edit
    usage: "/<command> {insert,delete,change} # TEXT"

permissions:
  trackrouter.changesign:
    description: Change lines on signs in-place
    default: op
  trackrouter.destination:
    description: Use the /destination command
    default: true
  trackrouter.junctions:
    description: Use the /junctions command
    default: op
  trackrouter.sign.junction.create:
    description: Create new junction signs
    default: true
  trackrouter.sign.junction.edit:
    description: Edit junction signs
    default: op
  trackrouter.sign.destination.create:
    description: Create new destination signs
    default: true
  trackrouter.sign.destination.use:
    description: Use destination signs
    default: true
  trackrouter.transfertool:
    description: Transfer your destination preference to a cart
    default: true
