name: PdxTrackRouter
main: com.gmail.emertens.PdxTrackRouter.PdxTrackRouter
version: 0.2
description: Automatically route minecarts down tracks. 
author: glguy
load: POSTWORLD
website: http://dev.bukkit.org/server-mods/pdxtrackrouter/

commands:
  destination:
    description: Set destination to take at junctions
    usage: /<command> [DIRECTION]
