name: PdxTrackRouter
main: com.gmail.emertens.PdxTrackRouter.PdxTrackRouter
version: 0.4
description: Automatically route minecarts down tracks. 
author: glguy
load: POSTWORLD
website: http://dev.bukkit.org/server-mods/pdxtrackrouter/

commands:
  destination:
    description: Set destination to take at junctions
    usage: /<command> [DIRECTION]
  changesign:
    description: Set a line on a sign
    usage: /<command> [1-4] TEXT
    permission: trackrouter.changesign

permissions:
  trackrouter.changesign:
    description: Change lines on signs in-place
    default: op
